# Este arquivo contém as queries SQL

NOTAS_PELO_BARRAMENTO = "SELECT COD_PROJETO FROM ELETROPROJ.PROJETO P WHERE SDE.ST_INTERSECTS(P.SHAPE,(SELECT PG.SHAPE FROM ELETROMAPA.PONTO_GEOGRAFICO PG WHERE PG.PGF_BARRAMENTO = '{}')) =1 ORDER BY PROJETO_ID"

ABRIR_NOTA = "UPDATE eletroproj.solicitacao_investimento SET SLI_STATUS_NOTA = '13' WHERE LTRIM(SLI_NOTA_SAP,0) IN ('{}')"

FECHAR_NOTA = "UPDATE eletroproj.solicitacao_investimento SET SLI_STATUS_NOTA = '14' WHERE LTRIM(SLI_NOTA_SAP,0) IN ('{}')"

ALTERAR_BARRAMENTO = "UPDATE ELETROMAPA.PONTO_GEOGRAFICO SET PGF_BARRAMENTO = '{}' WHERE PGF_BARRAMENTO = '{}'"

RETROCEDER_CARGA_1 = "UPDATE ELETROMAPA.PROJETO SET TB_STATUS_ID = '0' WHERE COD_PROJETO IN ('000{}')" 

RETROCEDER_CARGA_2 = "UPDATE ELETROMAPA.PROJETO SET carga_status = 'I' WHERE COD_PROJETO IN ('000{}')"

MUDAR_FASE_1 = "SELECT MSLINK FROM ELETROMAPA.TRECHO_SECUNDARIO WHERE MSLINK_INS = (SELECT MSLINK FROM ELETROMAPA.INSTALACAO_CARGA WHERE INT_NUM = '{}')"

MUDAR_FASE_2 = "UPDATE ELETROMAPA.TRECHO_DE_REDE SET tb_cdf_id = '{}' WHERE MSLINK = {}"

REMOVER_IP_1 = "SELECT MSLINK_TR FROM ELETROMAPA.V_NVS_TRECHO_DO_PG WHERE PGF_BARRAMENTO = '{}'"

REMOVER_IP_2 = "DELETE FROM ELETROMAPA.IP WHERE MSLINK_TR = {}"